// <auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

namespace SchedulerDatabase.Migrations
{
    public partial class AddAuthorAndDescription : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Author",
                table: "AESProfiles",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "AESProfiles",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Author",
                table: "AESProfiles");

            migrationBuilder.DropColumn(
                name: "Description",
                table: "AESProfiles");
        }
    }
}
