// <auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

namespace SchedulerDatabase.Migrations
{
    public partial class AddNumCores : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "NumCores",
                table: "AESProfiles",
                nullable: false,
                defaultValue: 1);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "NumCores",
                table: "AESProfiles");
        }
    }
}
