// <auto-generated/>

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SchedulerDatabase.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AESProfiles",
                columns: table => new
                {
                    ProfileId = table.Column<Guid>(nullable: false),
                    PlatformName = table.Column<string>(nullable: true),
                    ProviderName = table.Column<string>(nullable: true),
                    PlatformAccelerator = table.Column<int>(nullable: false),
                    TestedAESMode = table.Column<int>(nullable: false),
                    TestedAESBitLength = table.Column<int>(nullable: false),
                    TotalTestedByteSize = table.Column<int>(nullable: false),
                    TotalTestedEnergyJoules = table.Column<double>(nullable: false),
                    TotalTestTime = table.Column<TimeSpan>(nullable: false),
                    TestedFrequency = table.Column<int>(nullable: false),
                    AverageVoltage = table.Column<double>(nullable: false),
                    AverageCurrent = table.Column<double>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AESProfiles", x => x.ProfileId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AESProfiles");
        }
    }
}
