// <auto-generated/>

using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for AESGraphControl.xaml
    /// </summary>
    public partial class AESGraphControl : UserControl
    {
        public AESGraphControl()
        {
            InitializeComponent();
        }
    }
}
