// <auto-generated />

using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for DevicePickerControl.xaml
    /// </summary>
    public partial class DevicePickerControl : UserControl
    {
        public DevicePickerControl()
        {
            InitializeComponent();
        }
    }
}
