// <auto-generated/>

using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for EditControl.xaml
    /// </summary>
    public partial class EditControl : UserControl
    {
        public EditControl()
        {
            this.InitializeComponent();
        }
    }
}
