//<auto-generated/>

using System;
using System.Windows.Controls;


namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for EditSolarCellControl.xaml
    /// </summary>
    public partial class EditSolarCellControl : UserControl
    {
        public EditSolarCellControl()
        {
            this. InitializeComponent();
        }
    }
}
