//<auto-generated/>

using System;
using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for EditBatteryControl.xaml
    /// </summary>
    public partial class EditBatteryControl : UserControl
    {
        public EditBatteryControl()
        {
            InitializeComponent();
        }
    }
}
