// <auto-generated/>

using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for EditDialog.xaml
    /// </summary>
    public partial class EditDialog : UserControl
    {
        public EditDialog()
        {
            this.InitializeComponent();
        }
    }
}
