// <auto-generated/>

using System.Windows;
using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for EditControl.xaml
    /// </summary>
    public partial class EditControl : UserControl
    {
        public EditControl()
        {
            this.InitializeComponent();
        }

        private void saveButton_Click(object sender, RoutedEventArgs e)
        {
            missionPowerTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();
            encryptionPowerTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();
            datalinkPowerTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();

            missionEnergyTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();
            datalinkEnergyTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();
            encryptionEnergyTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();

            bytesTextBox.GetBindingExpression(TextBox.TextProperty).UpdateSource();
        }
    }
}
