// <auto-generated />

using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for ScheduleViewer.xaml
    /// </summary>
    public partial class ScheduleViewer : UserControl
    {
        public ScheduleViewer()
        {
            this.InitializeComponent();
        }
    }
}
