// <auto-generated

using System;
using System.Windows;
using System.Windows.Controls;

namespace SchedulerGUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for UserControl1.xaml
    /// </summary>
    public partial class TimeControl : UserControl
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeControl"/> class.
        /// </summary>
        public TimeControl()
        {
            this.InitializeComponent();
        }
    }
}
