// <auto-generated/>

using System.Windows;
using System.Windows.Controls;

namespace SchedulerGUI.Views
{
    /// <summary>
    /// Interaction logic for AboutDialog.xaml
    /// </summary>
    public partial class AboutDialog : UserControl
    {
        public AboutDialog()
        {
            this.InitializeComponent();
        }
    }
}
