// <auto-generated />

using System.Windows;

namespace SchedulerGUI.Views
{
    /// <summary>
    /// Interaction logic for addwindow.xaml
    /// </summary>
    public partial class addwindow : Window
    {
        public addwindow()
        {
            InitializeComponent();
        }
    }
}
