// <auto-generated />

using System.Windows.Controls;

namespace SchedulerGUI.Views
{
    /// <summary>
    /// Interaction logic for ImportToolDialog.xaml
    /// </summary>
    public partial class ImportToolDialog : UserControl
    {
        public ImportToolDialog()
        {
            InitializeComponent();
        }
    }
}
