// <auto-generated />

using Fluent;
using SchedulerGUI.ViewModels;
using System;
using System.Linq;

namespace SchedulerGUI.Views
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : IRibbonWindow
    {
        public MainWindow()
        {
            InitializeComponent();

            var dc = DataContext as MainWindowViewModel;
            timeline.ResetEvents(dc.TimelineEventPasses.ToList());
        }
    }
}
