// <auto-generated/>

using System.Windows;

namespace SchedulerGUI.Views
{
    /// <summary>
    /// Interaction logic for PlotWindow.xaml
    /// </summary>
    public partial class PlotWindow : Window
    {
        public PlotWindow()
        {
            InitializeComponent();
        }
    }
}
