// <auto-generated />

using System.Windows.Controls;

namespace SchedulerGUI.Views
{
    /// <summary>
    /// Interaction logic for ScheduleViewerDialog.xaml
    /// </summary>
    public partial class ScheduleViewerDialog : UserControl
    {
        public ScheduleViewerDialog()
        {
            this.InitializeComponent();
        }
    }
}
